version: "3"
services:
  web: 
    build:
      context: ./web
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - "./web/app:/app" 
      # exclude volumes
      - /app/node_modules
    ports:
      - 3000:3000
    container_name: "nuxt-sample" # Name the container
    tty: true
    stdin_open: true